name: svmapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.3
  dynamic_theme: ^1.0.1
  shared_preferences: ^0.5.12+4
  carousel_slider: ^2.2.1
  font_awesome_flutter: ^8.10.1
  easy_web_view: ^1.3.1
  url_launcher: ^5.7.10
  
  line_icons: ^0.2.0
  responsive_scaffold: ^1.3.0+2
  
  #webview_flutter: 
  # google_maps: ">=3.0.0 <4.0.0"
  # google_maps_flutter: ^0.5.28
  # google_maps_flutter_web: ^0.1.0
  #cloud_firestore: ^0.13.4
  #image_picker: ^0.6.3+4
  #firebase_storage: ^3.1.3
  #random_string: ^2.0.1
  #cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
